AllCops:   
  Exclude:     
    - 'db/**/*'     
    - 'config/**/*'     
    - 'libs/**/*'
    - 'Gemfile'
    - 'log/**/*'
Layout/DefEndAlignment:
  Exclude:

Layout/LeadingEmptyLines:
  Exclude:
    - 'Gemfile'

Naming/ClassAndModuleCamelCase:
  Enabled: false

Style/Documentation:
    Enabled: false

Style/FrozenStringLiteralComment:
   Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20