source 'https://rubygems.org'

gem 'appium_console', '2.12.0'
gem 'appium_lib', '~> 10.5.0'
gem 'cucumber'
gem 'httparty'
gem 'pry', '~> 0.12.0'
gem 'report_builder'
gem 'rspec'
gem 'faker'
gem 'rubocop'
